services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    command: ["uvicorn", "main:app", "--reload", "--proxy-headers", "--host", "0.0.0.0", "--port", "${PORT}"]
    volumes:
      - "./${APPLICATION_DIR}:/root/${APPLICATION_DIR}"
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - database

  crawler:
    build:
      context: .
      dockerfile: crawler/Dockerfile
    container_name: pidcheck_crawler
    command: [ "poetry", "run", "scrapy", "runspider", "pidcheck/spiders/pid_spider.py" ]
    ports:
      - "${CRAWLER_PORT}:${CRAWLER_PORT}"
    depends_on:
      - redis


  database:
    image: postgres:latest
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
